#!/usr/bin/env bash

if [ "$(uname)" = "Darwin" ]; then
  /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install.sh)"

  test -e /opt/homebrew/bin/brew && eval "$(/opt/homebrew/bin/brew shellenv)"
fi

git clone https://github.com/asdf-vm/asdf.git ~/.asdf --branch v0.10.2
source "$HOME/.asdf/asdf.sh"

if [ "$(uname)" = "Darwin" ]; then
  # nodejs
  brew install gpg gawk

  # php build
  brew install autoconf automake bison freetype gd gettext icu4c krb5 libedit libiconv libjpeg libpng libxml2 libzip pkg-config re2c zlib libsodium imagemagick gmp

  brew tap homebrew/cask-fonts
  brew install --cask font-hack-nerd-font
  brew install --cask font-cica

  brew install trash git-flow-avh
  brew install zsh tmux neovim git fzf bat ripgrep ghq fd translate-shell

  sudo bash -c "echo '$(brew --prefix)/bin/zsh' >> /etc/shells"
  sudo chsh -s "$(brew --prefix)/bin/zsh" "$USER"

  "$(brew --prefix)/opt/fzf/install"
elif [ "$(uname)" = "Linux" ]; then
  sudo apt update

  # nodejs
  sudo apt install -y dirmngr gpg curl gawk

  # php build
  sudo apt install -y autoconf bison build-essential curl gettext git libgd-dev libcurl4-openssl-dev libedit-dev libicu-dev libjpeg-dev libmysqlclient-dev libonig-dev libpng-dev libpq-dev libreadline-dev libsqlite3-dev libssl-dev libxml2-dev libzip-dev openssl pkg-config re2c zlib1g-dev

  sudo apt install -y zsh tmux neovim git fzf bat ripgrep fd-find

  asdf plugin add golang
  go_version=$(asdf list all golang | rg '^[0-9]+\.[0-9]+\.[0-9]+$' | tail -1)
  asdf install golang "$go_version"
  asdf global golang "$go_version"

  go install github.com/x-motemen/ghq@latest

  sudo chsh -s "/usr/bin/zsh" "$USER"
fi

# ghq
git config --global ghq.root ~/.ghq

# nvim plug
curl -fLo ~/.local/share/nvim/site/autoload/plug.vim --create-dirs https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim

# oh my zsh
sh -c "$(curl -fsSL https://raw.githubusercontent.com/ohmyzsh/ohmyzsh/master/tools/install.sh) --unattended"

mkdir -p "$HOME/.zsh"
git clone https://github.com/sindresorhus/pure.git "$HOME/.zsh/pure"

git clone https://github.com/zsh-users/zsh-completions ${ZSH_CUSTOM:=~/.oh-my-zsh/custom}/plugins/zsh-completions
git clone https://github.com/zsh-users/zsh-autosuggestions ${ZSH_CUSTOM:-~/.oh-my-zsh/custom}/plugins/zsh-autosuggestions
git clone https://github.com/zsh-users/zsh-syntax-highlighting.git ${ZSH_CUSTOM:-~/.oh-my-zsh/custom}/plugins/zsh-syntax-highlighting

# rust
curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh -s -- -y
source "$HOME/.cargo/env"
cargo install exa

make deploy
