[tools]
bun = "1"
gitleaks = "8"
go = "1"
"go:golang.org/x/tools/gopls" = "latest"
node = "24"
"npm:@fission-ai/openspec" = "latest"
"npm:r2-lfs" = "0.4.0"
"npm:typescript" = "latest"
"npm:typescript-language-server" = "latest"
pnpm = "11"
python = "3.14"
ruby = "4"
